# Generated by Django 5.2.4 on 2025-07-28 18:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issqn_fixo', models.BooleanField(default=False, verbose_name='ISSQN fixo para todos os regimes')),
                ('aliquota_issqn', models.DecimalField(decimal_places=4, default=Decimal('0.03'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.02')), django.core.validators.MaxValueValidator(Decimal('0.05'))], verbose_name='Alíquota de ISSQN no Município')),
                ('receita_mensal', models.DecimalField(decimal_places=2, default=Decimal('25000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Receita Mensal Média')),
                ('despesas_dedutiveis', models.DecimalField(decimal_places=2, default=Decimal('15025.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Despesas Dedutíveis (Pessoa Física)')),
                ('folha_pagamento_pf', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Folha de Pagamento PF')),
                ('pro_labore', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pró-labore Registrado')),
                ('folha_pagamento_empresa', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Folha de Pagamento Empresa')),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.usuario')),
            ],
            options={
                'verbose_name': 'Cálculo Tributário',
                'verbose_name_plural': 'Cálculos Tributários',
                'ordering': ['-data_calculo'],
            },
        ),
    ]
