# Generated by Django 5.2.4 on 2025-07-30 18:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculotributario',
            name='aliquota_issqn',
            field=models.DecimalField(decimal_places=4, default=Decimal('3'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('2')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Alíquota de ISSQN no Município'),
        ),
    ]
